name: Publish to VS Code Marketplace

on:
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Package extension
        run: npm run package

      - name: Login to VS Code Marketplace
        run: echo "{\"publishers\":[{\"name\":\"tfdocs\",\"pat\":\"${{ secrets.VSCE_PAT }}\"}]}" > .vsce

      - name: Publish to VS Code Marketplace
        run: npm run publish
